# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - pip install uv
    - uv sync --extra docs
    - uv run sphinx-build -b html docs docs/_build/html
    - mv docs/_build/html $READTHEDOCS_OUTPUT
