name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
      - uses: psf/black@24.4.2
        with:
          options: "--check --verbose"
          src: "./src"
          jupyter: true
